## Class of data types

### In case of python, all data types are class, when we create an variable of that type, it will be an object of that class

In [ ]:
import tensorflow

In [1]:
import pyspark

In [2]:
Datatype(L)

NameError: name 'Datatype' is not defined

# class have two thing
1. data or property 
2. Function or behavior

## Python Naming Conventions
### 1. General
Avoid using names that are too general or too wordy. Strike a good balance between the two.
Bad: data_structure, my_list, info_map, dictionary_for_the_purpose_of_storing_data_representing_word_definitions
Good: user_profile, menu_options, word_definitions
Don’t be a jackass and name things “O”, “l”, or “I”
When using CamelCase names, capitalize all letters of an abbreviation (e.g. HTTPServer)
### 2. Packages
Package names should be all lower case
When multiple words are needed, an underscore should separate them
It is usually preferable to stick to 1 word names
### 3. Modules
Module names should be all lower case
When multiple words are needed, an underscore should separate them
It is usually preferable to stick to 1 word names
### 4. Classes
Class names should follow the UpperCaseCamelCase convention
Python’s built-in classes, however are typically lowercase words
Exception classes should end in “Error”
### 5. Global (module-level) Variables
Global variables should be all lowercase
Words in a global variable name should be separated by an underscore
### 6. Instance Variables
Instance variable names should be all lower case
Words in an instance variable name should be separated by an underscore
Non-public instance variables should begin with a single underscore
If an instance name needs to be mangled, two underscores may begin its name
### 7. Methods
Method names should be all lower case
Words in an method name should be separated by an underscore
Non-public method should begin with a single underscore
If a method name needs to be mangled, two underscores may begin its name
### 8. Method Arguments
Instance methods should have their first argument named ‘self’.
Class methods should have their first argument named ‘cls’
### 9. Functions
Function names should be all lower case
Words in a function name should be separated by an underscore
### 10. Constants
Constant names must be fully capitalized
Words in a constant name should be separated by an underscore

### Class name is in CamelCase
### variable and function name are in snake_case

In [ ]:
Class Car:
    def __init__(self,number_of_weels,color)

In [ ]:
#function verses methods
Function just outside the class
methods is a function which is define inside the class

## Atm software

In [42]:
class Atm:
    
    #Constructor
    #special method/magic method/ Dunder methods
    def __init__(self):
        self.pin=''
        self.balance=0
        print(id(self))
        self.menu()
    
    
    def menu(self):
        user_input=input('''
        Hello, how would you like to proceed?
        1. Enter 1 to create a pin.
        2. Enter 2 to deposit
        3. Enter 3 to withdraw
        4. Enter 4 to check balance
        5. Enter 5 to exit''')
        if user_input=='1':
            print('Create Pin')
            self.create_pin()
        elif user_input=='2':
            print('Deposit')
            self.deposite()
        elif user_input=='3':
            print('withdraw')
            self.withdraw()
        elif user_input=='4':
            print('balance')
            self.check_balance()
        elif user_input=='5':
            print('bye')
        else:
            print("incorrect input")
            
            
    def create_pin(self):
        self.pin=input("Enter your pin")
        print("pin set successfully")
        

        
        
    def deposite(self):
        temp=input('Enter your pin')
        if temp==self.pin:
            ammount=int(input('Enter your ammount'))
            self.balance=self.balance+ammount
            print("Deposit successful")
        else:
            print("invalid pin")
    
    
    def withdraw(self):
        temp=input('Enter your pin')
        if temp==self.pin:
            ammount=int(input('Enter your ammount'))
            if self.balance>=ammount:
                self.balance=self.balance-ammount
                print("withdraw successful")
            else:
                print('Not enough balance for withdrawal')
        else:
            print("invalid pin")
            
    def check_balance(self):
        temp=input('Enter your pin')
        if temp==self.pin:
            print('Balance:',self.balance)
            
            

Constructor: it is a special methods which is autumetically
run while creating the object

In [43]:
a=Atm()

140267335502384

        Hello, how would you like to proceed?
        1. Enter 1 to create a pin.
        2. Enter 2 to deposit
        3. Enter 3 to withdraw
        4. Enter 4 to check balance
        5. Enter 5 to exit5
bye


In [37]:
a.menu()


        Hello, how would you like to proceed?
        1. Enter 1 to create a pin.
        2. Enter 2 to deposit
        3. Enter 3 to withdraw
        4. Enter 4 to check balance
        5. Enter 5 to exit2
Deposit
Enter your pin1234
Enter your ammount1234567
Deposit successful


In [38]:
a.menu()


        Hello, how would you like to proceed?
        1. Enter 1 to create a pin.
        2. Enter 2 to deposit
        3. Enter 3 to withdraw
        4. Enter 4 to check balance
        5. Enter 5 to exit4
balance
Enter your pin1234
Balance: 1234567


In [44]:
# create your own data type
Class for Fraction Data type 

In [282]:
def gcd(n, d):
    while n != d:
        if n > d:
            n = n - d
        else:
            d = d - n
    return n

def simplify(n,d):
    num = int(n / gcd(abs(n), abs(d)))
    denom = int(d / gcd(abs(n), abs(d)))
    if denom < 0:
        denom = abs(denom)
        num = -1*num
    return num,denom
    
class Fraction:
    def __init__(self,n,d):
        if(d!=0):
            n,d=simplify(n,d)
            self.num=n
            self.den=d
        else:
            raise ZeroDivisionError
        
    def __str__(self):
        if self.den!=1:
            return "{}/{}".format(self.num,self.den)
        else:
            return "{}".format(self.num,self)
            
        
    def __add__(self,other):
        temp_num=self.num*other.den+other.num*self.den
        temp_den=self.den*other.den
        temp_num,temp_den=simplify(temp_num,temp_den)
        if temp_den!=1:
            return "{}/{}".format(temp_num,temp_den)
        else:
            return "{}".format(temp_num)
    
    def __sub__(self,other):
        temp_num=self.num*other.den-other.num*self.den
        temp_den=self.den*other.den
        temp_num,temp_den=simplify(temp_num,temp_den)
        if temp_den!=1:
            return "{}/{}".format(temp_num,temp_den)
        else:
            return "{}".format(temp_num)
    def __mul__(self,other):
        temp_num=self.num*other.num
        temp_den=self.den*other.den
        temp_num,temp_den=simplify(temp_num,temp_den)
        if temp_den!=1:
            return "{}/{}".format(temp_num,temp_den)
        else:
            return "{}".format(temp_num)
    def __truediv__(self,other):
        temp_num=self.num*other.den
        temp_den=self.den*other.num
        temp_num,temp_den=simplify(temp_num,temp_den)
        if temp_den!=1:
            return "{}/{}".format(temp_num,temp_den)
        else:
            return "{}".format(temp_num)
    def __eq__(self,other):
        if self.num*other.den==other.num*self.den:
            return True
        else:
            return False
    
    
    def __lt__(self,other):
        if self.num*other.den<other.num*self.den:
            return True
        else:
            return False
    def __le__(self,other):
        if self.num*other.den<=other.num*self.den:
            return True
        else:
            return False
    def __gt__(self,other):
        if self.num*other.den>other.num*self.den:
            return True
        else:
            return False
    def __ge__(self,other):
        if self.num*other.den>=other.num*self.den:
            return True
        else:
            return False
    def __ne__(self,other):
        if self.num*other.den!=other.num*self.den:
            return True
        else:
            return False
        
    
    
        
        

In [300]:
x=Fraction(3,4)

In [313]:
type(x)

int

In [312]:
2/3+23

23.666666666666668

In [310]:
x.__add__(4)

6

In [296]:
id(y)

140266548403120

In [294]:
y=Fraction(3,1)

In [267]:
print(y)

1/16


In [268]:
print(x+y)

49/16


In [269]:
print(x-y)

47/16


In [270]:
print(x*y)

3/16


In [271]:
print(x/y)

48


In [272]:
(x<=y)

False

In [178]:
a=4
b=3

In [179]:
a.__eq__(b)

False

In [90]:
def gcd(n, d):
    while n != d:
        if n > d:
            n = n - d
        else:
            d = d - n
    return n
class Fraction:
    def __init__(self, n, d):
        self.num = int(n / gcd(abs(n), abs(d)))
        self.denom = int(d / gcd(abs(n), abs(d)))
        if self.denom < 0:
            self.denom = abs(self.denom)
            self.num = -1*self.num
        elif self.denom == 0:
            raise ZeroDivisionError

    def Add(self, other):
        return self.num*other.denom + self.denom*other.num, self.denom*other.denom
    def Sub(self, other):
        return self.num*other.denom - self.denom*other.num, self.denom*other.denom
    def Mul(self, other):
        return self.num*other.num, self.denom*other.denom
    def Div(self, other):
        return self.num*other.denom, self.denom*other.num
    def __str__(self):
        if type(self) is tuple:
            if self[1] < 0:
                return '%s/%s' %(self[0], -1*self[1])
            else:
                return '%s/%s' %(self[0], self[1])
        elif self.denom == 1:
            return str(self.num)
        else:
            return '%s/%s' %(self.num, self.denom)
    def __cmp__(self, arg):
        if self > arg:
            return -1
        elif self == arg:
            return 0
        else:
            return 1
    def __nonzero__(self):
        if self != 0:
            return True
        else:
            return False
def main():
    f1 = Fraction(2,-2)
    f2 = Fraction(3,-4)
    f3 = Fraction.Add(f1,f2)
    f4 = Fraction.Sub(f1,f2)
    f5 = Fraction.Mul(f1,f2)
    f6 = Fraction.Div(f1,f2)
    f8 = 0
    print(Fraction.__cmp__(f4,f4),Fraction.__str__(f3),Fraction.__str__(f4),Fraction.__str__(f5),Fraction.__str__(f6), Fraction.__str__(f1), Fraction.__str__(f2))
    if Fraction.__nonzero__(f8):
        print("It is a fraction")
    else:
        print("It is not a fraction")
    return 0
if __name__ == '__main__':
    main()


0 -7/4 -1/4 3/4 -4/3 -1 -3/4
It is not a fraction


In [328]:
# importing module
import pyspark
  
# importing sparksession from pyspark.sql module
from pyspark.sql import SparkSession
  
# creating sparksession and giving an app name
spark = SparkSession.builder.appName('sparkdf').getOrCreate()
  
# Column names for the dataframe
columns = ["Brand", "Product"]
  
# Row data for the dataframe
data = [
    ("HP", "Laptop"),
    ("Lenovo", "Mouse"),
    ("Dell", "Keyboard"),
    ("Samsung", "Monitor"),
    ("MSI", "Graphics Card"),
    ("Asus", "Motherboard"),
    ("Gigabyte", "Motherboard"),
    ("Zebronics", "Cabinet"),
    ("Adata", "RAM"),
    ("Transcend", "SSD"),
    ("Kingston", "HDD"),
    ("Toshiba", "DVD Writer")
]
  
# Create the dataframe using the above values
prod_df = spark.createDataFrame(data=data,
                                schema=columns)
  
# View the dataframe
prod_df.show()

RuntimeError: Java gateway process exited before sending its port number

In [327]:
import pyspark 
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
df = sprk.createDataFrame(data)

AttributeError: 'SparkConf' object has no attribute 'createDataFrame'

In [316]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

a = np.array([[1,2,3],[100,2,3],[1,2,3]])
b = np.array([[10,20,30]])
c = np.array([[5, 10, 15]])

""" Scale on all datasets together in one batch """
offline_scaler = MinMaxScaler()
offline_scaler.fit(np.vstack((a, b, c)))                # fit on whole data at once
a_offline_scaled = offline_scaler.transform(a)
b_offline_scaled = offline_scaler.transform(b)
c_offline_scaled = offline_scaler.transform(c)
print('Offline scaled')
print(a_offline_scaled)
print(b_offline_scaled)
print(c_offline_scaled)

""" Scale on all datasets together in minibatches """
online_scaler = MinMaxScaler()
online_scaler.partial_fit(a)                            # partial fit 1
online_scaler.partial_fit(b)                            # partial fit 2
online_scaler.partial_fit(c)                            # partial fit 3
a_online_scaled = online_scaler.transform(a)
b_online_scaled = online_scaler.transform(b)
c_online_scaled = online_scaler.transform(c)
print('Online scaled')
print(a_online_scaled)
print(b_online_scaled)
print(c_online_scaled)

Offline scaled
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
[[0.09090909 1.         1.        ]]
[[0.04040404 0.44444444 0.44444444]]
Online scaled
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
[[0.09090909 1.         1.        ]]
[[0.04040404 0.44444444 0.44444444]]
